[package]
name = "helix_mode_setting"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "GPL-3.0-or-later"

[lib]
path = "src/helix_mode_setting.rs"

[dependencies]
anyhow.workspace = true
gpui.workspace = true
settings.workspace = true
workspace-hack.workspace = true
